# type: 0 -> general, 1 -> skill, 2 -> ultimate
# effect: 0 -> damage, 1 -> heal
# level: 0 -> low, 1 -> mid, 2 -> high, 3 -> ultimate
- name: 拳擊
  type: 0
  effect: 0
  level: 0
- name: 踢擊
  type: 0
  effect: 0
  level: 0
- name: 砍一刀
  type: 0
  effect: 0
  level: 1
- name: 開一槍
  type: 0
  effect: 0
  level: 1